import net from 'net';
import tls from 'tls';
import { resolveRouterTarget } from '../utils/network.js';

function encodeLength(len){if(len<0x80)return Buffer.from([len]);if(len<0x4000){const b=Buffer.alloc(2);b.writeUInt16BE(len|0x8000);return b;}if(len<0x200000){const b=Buffer.alloc(3);b[0]=(len>>16)|0xc0;b[1]=(len>>8)&0xff;b[2]=len&0xff;return b;}if(len<0x10000000){const b=Buffer.alloc(4);b.writeUInt32BE(len|0xe0000000);return b;}const b=Buffer.alloc(5);b[0]=0xf0;b.writeUInt32BE(len,1);return b;}
function encodeWord(word){const data=Buffer.from(String(word),'utf8');return Buffer.concat([encodeLength(data.length),data]);}
function encodeSentence(words){return Buffer.concat([...words.map(encodeWord),Buffer.from([0])]);}
function decodeLength(buf,offset){if(offset>=buf.length)return null;const b0=buf[offset];if((b0&0x80)===0)return{length:b0,size:1};if((b0&0xc0)===0x80){if(offset+1>=buf.length)return null;return{length:((b0&0x3f)<<8)+buf[offset+1],size:2};}if((b0&0xe0)===0xc0){if(offset+2>=buf.length)return null;return{length:((b0&0x1f)<<16)+(buf[offset+1]<<8)+buf[offset+2],size:3};}if((b0&0xf0)===0xe0){if(offset+3>=buf.length)return null;return{length:((b0&0x0f)<<24)+(buf[offset+1]<<16)+(buf[offset+2]<<8)+buf[offset+3],size:4};}if(b0===0xf0){if(offset+4>=buf.length)return null;return{length:buf.readUInt32BE(offset+1),size:5};}throw new Error('Invalid RouterOS length encoding');}
function parseSentences(buf){const sentences=[];let offset=0,current=[];while(offset<buf.length){const li=decodeLength(buf,offset);if(!li)break;if(li.length===0&&li.size===1){offset++;if(current.length){sentences.push(current);current=[];}continue;}offset+=li.size;if(offset+li.length>buf.length)break;const word=buf.slice(offset,offset+li.length).toString('utf8');offset+=li.length;if(word.startsWith('!'))current.push({type:word});else if(word.startsWith('=')){const eq=word.indexOf('=',1);current.push(eq===-1?{type:'attr',key:word.slice(1),value:''}:{type:'attr',key:word.slice(1,eq),value:word.slice(eq+1)});}else if(word.startsWith('.'))current.push({type:'query',key:word});else current.push({type:'word',value:word});}return{sentences,rest:offset<buf.length?buf.slice(offset):Buffer.alloc(0)};}
function sentenceToObject(sentence){const obj={_type:null};for(const item of sentence){if(item.type?.startsWith('!'))obj._type=item.type;else if(item.type==='attr')obj[item.key]=item.value;}return obj;}

export class RouterOSClient{
 constructor({host,port=8728,user,password,timeout=15000,secure=false}){this.host=host;this.port=Number(port)||8728;this.user=user;this.password=password;this.timeout=timeout;this.secure=Boolean(secure);this.tlsServerName=host;this.rejectUnauthorized=process.env.ROUTER_TLS_REJECT_UNAUTHORIZED!=='false';this.socket=null;this.buffer=Buffer.alloc(0);this.pending=[];this.connected=false;}
 async connect(){const address=await resolveRouterTarget(this.host);return new Promise((resolve,reject)=>{let settled=false;const finishReject=e=>{if(settled)return;settled=true;clearTimeout(timer);this._destroy();reject(e);};const finishResolve=()=>{if(settled)return;settled=true;clearTimeout(timer);resolve();};const timer=setTimeout(()=>finishReject(new Error(`Connection timed out after ${this.timeout}ms`)),this.timeout);const options=this.secure?{host:address,port:this.port,servername:this.tlsServerName,rejectUnauthorized:this.rejectUnauthorized}:{host:address,port:this.port};this.socket=this.secure?tls.connect(options):net.createConnection(options);const onConnected=async()=>{if(this.connected||settled)return;try{this.connected=true;this.socket.setTimeout(this.timeout);this.socket.on('data',c=>this._onData(c));this.socket.on('error',e=>this._failAll(e));this.socket.on('close',()=>{this.connected=false;this._failAll(new Error('Connection closed'));});this.socket.on('timeout',()=>{this._destroy();this._failAll(new Error('Socket timeout'));});await this._login();finishResolve();}catch(e){finishReject(e);}};this.socket.once(this.secure?'secureConnect':'connect',onConnected);this.socket.once('error',finishReject);});}
 async _login(){const result=await this.write('/login',[`=name=${this.user}`,`=password=${this.password}`]);const reply=result.find(r=>r._type==='!done'||r._type==='!trap');if(reply?._type==='!trap')throw new Error(reply.message||'Login failed');if(!reply)throw new Error('Login failed — no response from router');}
 write(command,params=[]){return new Promise((resolve,reject)=>{if(!this.connected||!this.socket)return reject(new Error('Not connected'));this.pending.push({resolve,reject,results:[]});this.socket.write(encodeSentence([command,...params]));});}
 _onData(chunk){this.buffer=Buffer.concat([this.buffer,chunk]);const {sentences,rest}=parseSentences(this.buffer);this.buffer=rest;for(const sentence of sentences){const obj=sentenceToObject(sentence),current=this.pending[0];if(!current)continue;if(obj._type==='!re')current.results.push(obj);else if(obj._type==='!done'){this.pending.shift();current.resolve(current.results.length?current.results:[obj]);}else if(obj._type==='!trap'||obj._type==='!fatal'){this.pending.shift();const err=new Error(obj.message||obj['=message']||'RouterOS error');err.trap=obj;current.reject(err);}}}
 _failAll(err){while(this.pending.length)this.pending.shift().reject(err);}
 _destroy(){this.connected=false;if(this.socket){try{this.socket.destroy();}catch{}this.socket=null;}}
 close(){this._destroy();}
}
export async function withRouterOS(opts,fn){const client=new RouterOSClient(opts);try{await client.connect();return await fn(client);}finally{client.close();}}
